#!/usr/bin/env bash

readonly VERSION='decrypt 0.1.0'

usage() {
    echo
    echo "$(ansi bold Decrypt a file using age)."
    echo
    echo "Usage: $(ansi bold_blue sage ${scriptName}) [OPTIONS] -i IDENTITY PATH"
    echo
    echo "Decrypted tar files will be unpacked by default into a new directory using the filename without any extension."
    echo
    echo "Options:"
    echo
    echo "    -i, --identity IDENTITY  Decrypt using the identity (private key) file at IDENTITY. May be repeated."
    echo "    -u, --unpack-to UNPACK   Write tar content to the directory at path UNPACK."
    echo "    -n, --no-unpack          Do not unpack tar files."
    echo "    -o, --output OUTPUT      Write the result to the file at path OUTPUT."
    echo "    -f, --force              Replace any existing output file(s) without asking."
    echo "    -q, --quiet              Don't write progress."
    echo "    -h, --help               Display usage."
    bye "${@}"
}

main() {
    init "${@}"
    decryptFile
    unpackFile
}

init() {
    readonly scriptName=$(basename "${0}")

    file=
    force=
    unpack=yes
    unpackDir=
    identities=
    decryptedFile=
    quiet=

    while (( ${#} > 0 )); do
        case "${1}" in
            -i|--identity) shift; assertFile "${1}"; appendVar identities "-i ${1}" ;;
            -u|--unpack-dir) shift; unpackDir="${1}" ;;
            -n|--no-unpack) unset unpack ;;
            -o|--output) shift; decryptedFile="${1}" ;;
            -f|--force) force="yes" ;;
            -q|--quiet) quiet="yes" ;;
            -h | --help) usage ;;
            --version) version "${VERSION}" ;;
            -*) usage "Unknown arg: ${1}" ;;
           *) setFile "${1}"
        esac
        shift
    done

    [[ ${identities} ]] || fail "no identities specified"
    [[ ${file} ]] || fail "no file provided"
    [[ ${decryptedFile} ]] || decryptedFile=$(basename -- "${file}" .${ageFileExtension})
}

setFile() {
    [[ ${file} ]] && usage "PATH can only be specified once"
    file="${1}"
    [[ -e ${file} ]] || fail "${file} not found"
    [[ -f ${file} ]] || fail "${file} is not a file"
    [[ ${file} == *.${ageFileExtension} ]] || fail "expected file with '.${ageFileExtension}' extension, got ${file}"
}

progress() {
    [[ ${quiet} ]] || echo "${*}"
}

decryptFile() {
    [[ -f ${decryptedFile} ]] && replaceOutputFile "${decryptedFile}"
    progress "Decrypting $(ansi cyan ${file}) to $(ansi bold ${decryptedFile})"
    rage -d ${identities} "${file}" -o "${decryptedFile}" 2> >(redStream) || fail
}

unpackFile() {
    if [[ ${unpack} ]]; then
        if tar tf "${decryptedFile}" &> /dev/null; then
            setUnpackDir
            progress "Unpacking $(ansi cyan ${decryptedFile}) to $(ansi bold ${unpackDir})"
            tar -xf "${decryptedFile}" -C "${unpackDir}"
        fi
    fi
}

setUnpackDir() {
    if [[ ! ${unpackDir} ]]; then
        unpackDir="$(echo "${decryptedFile}" | cut -d'.' -f1)-content"
    fi
    [[ -e ${unpackDir} ]] && replaceOutputFile "${unpackDir}"
    mkdir -p "${unpackDir}" || fail
}

replaceOutputFile() {
    local reply
    local target="${1}"
    if [[ ! ${force} ]]; then
        echo "$(ansi bold ${target}) already exists."
        read -p "$(ansi red Replace all output files?) y/n: " reply
        [[ ${reply} != "y" ]] && exit 0
        force="yes"
    fi
    rm -rf "${target}" || fail
    progress "Deleted $(ansi bold ${target})"
}

source rayvn.up 'rayvn/core' 'rayvn/age'

main "${@}"
