#!/usr/bin/env bash

require 'rayvn/core' 'rayvn/safe-env' 'valt/age' 'valt/password'

usage() {
    echo
    echo "$(ansi bold Generate an age public key pair and backup documentation)."
    echo
    echo "Usage: $(ansi bold_blue valt keys) [OPTIONS]"
    echo
    echo "Private keys are encrypted and a strong passphrase is $(ansi bold_green highly) encouraged; advice and an opportunity to"
    echo "generate one will be offered."
    echo
    echo "A PDF file will be created containing your keys, also in encrypted form, to serve as a backup for you and/or your"
    echo "successors. Detailed usage instructions are included. Keys are represented as a QR code and again in a text format"
    echo "(often called \"paper keys\"). Content will be personalized: you will be prompted to edit a $(ansi blue key.info) file".
    echo
    echo "Space is provided in the document for you to record your passphrase by hand. Please do so, and then:"
    echo
    echo "      $(ansi bold store the document in a secure location such as a safe deposit box or fire safe!)"
    echo
    echo "Better, store copies in multiple secure places, perhaps also with a trusted friend or family member."
    echo
    echo "Options"
    echo
    echo "    -p, --prefix PREFIX           Use PREFIX for key file names. Defaults to ${USER}."
    echo "    -f, --force                   Overwrite existing files."
    echo "    --no-verify                   Do not verify keys."
    echo "    --no-advice                   Do not show passphrase advice."
    echo "    -q, --quick                   Do not verify keys or show passphrase advice."
    echo "    -t, --template TEMPLATE       Use the TEMPLATE markdown file instead of the default for PDF generation."
    echo "    -c, --css CSS                 Apply style overrides from the CSS file for PDF generation."
    echo "    -h, --help                    Display usage and exit."
    echo
    echo "$(ansi bold Document Customization)"
    echo
    echo "The HTML template can be changed from the default and CSS style overrides can be applied. The default template"
    echo "and primary CSS file can be found in the $(ansi blue ${valtEtcDir}) directory."
    echo
    echo "Template substitutions are performed with variables defined in the $(ansi blue key.info) file. Note that keys"
    echo "prefixed with an underscore are reserved for system use."
    echo
    echo "The template can be specified with the --template option, and default styles can be extended using the --css option."
    bye
}

main() {
    init "${@}"
    createKeys
    if [[ ${keyInfoFile} ]]; then
        createKeyDocument
    fi
    echo
}

init() {
    declare -gr keyInfoTemplateFile="${valtEtcDir}/key-info-template.sh"
    declare -gr keyInfoFile="${valtConfigDir}/key.info"
    declare -gr cssMainFileName="key-doc.css"
    declare -gr logoFileName="phoggy.png"
    declare -gr assetFiles=("${cssMainFileName}" "${logoFileName}")
    declare -gr cssOverrideFileName='override.css'
    declare -gr htmlFileName='note.html'
    declare -gr qrCodeFileName='qr.png'
    qrCodeFile=
    armoredKey=

    # Options
    htmlTemplateFile="${valtEtcDir}/key-doc-template.html"
    cssOverrideFile=
    htmlFile=
    prefix="${USER}"
    htmlFile=

    # Flags
    declare -i force=0
    declare -i showKeyAdvice=1
    declare -i verifyKeys=1

    while (( ${#} > 0 )); do
        case "${1}" in
            --) ;;
            -p | --prefix) shift; setPrefix "${1}";;
            -t | --template) shift; setFileVar templateFile "${1}" "TEMPLATE" ;;
            -c | --css) shift; setFileVar cssOverrideFile "${1}" "CSS" ;;
            --no-verify) verifyKeys=0 ;;
            --no-advice) showKeyAdvice=0 ;;
            -q | --quick) showKeyAdvice=0; verifyKeys=0 ;;
            -f | --force) force=1 ;;
            -h | --help | help) usage ;;
            -*) usage "Unknown option: ${1}" ;;
        esac
        shift
    done

    privateKeyFile="${valtConfigDir}/${prefix}.key"
    publicKeyFile="${valtConfigDir}/${prefix}-public.key"

    # TODO see Data Model in rayvn note !!! ------------------------------------------------

    ensureKeyInfo
    documentsFile="${valtConfigDir}/${prefix}-key.pdf"

    # TODO ---------------------------------------------------------------------------------

    if (( force )); then
        rm "${publicKeyFile}" "${privateKeyFile}" 2> /dev/null
    else
        assertFileDoesNotExist "${privateKeyFile}"
        assertFileDoesNotExist "${publicKeyFile}"
    fi
}

setPrefix() {
    assertValidFileName "${1}"
    prefix="${1}"
}

ensureKeyInfo() {
    local status="has not been"

    if [[ ! -f "${keyInfoFile}" ]]; then
        cp "${keyInfoTemplateFile}" "${keyInfoFile}" || fail
        status="must be"
    else
        sourceSafeStaticVars "${keyInfoFile}"
        assertKeyInfoVar closing author completed
        [[ $(declare -p contacts 2> /dev/null) ]] || fail "${keyInfoFile} is missing the 'contacts' array variable."
        (( ${#contacts[@]} )) || fail "${keyInfoFile} must include one contact in the 'contacts' array variable."
        if [[ ${completed} == yes ]]; then
            return 0
        fi
    fi

    echo
    echo "The $(ansi bold key.info) file at $(ansi blue ${valtConfigDir}) ${status} completed."
    echo "Please edit and complete it before proceeding."
    bye
}

assertKeyInfoVar() {
    while (( ${#} > 0 )); do
        local varName="${1}"
        [[ -v ${varName} ]] || fail "${keyInfoFile} is missing the '${varName}' variable."
        [[ $(declare -p "${varName}" 2> /dev/null) ]] || fail "${keyInfoFile} '${varName}' variable cannot be empty."
        shift
    done
}

createKeys() {
    echo
    echo "$(ansi bold Generating keys)"
    if (( showKeyAdvice )); then
        echo
        showAgeKeyPairAdvice
        local reply
        read -t ${inputTimeout} -p "Would you like help generating a passphrase? (y/n): " reply
        echo
        [[ ${reply,,} == 'y' ]] && generatePass
    fi
    createAgeKeyPair "${privateKeyFile}" "${publicKeyFile}" _PHRASE || fail
    echo
    echo "Public key (aka 'recipient') file: $(ansi cyan ${publicKeyFile})"
    echo "Private key (aka 'identity') file: $(ansi cyan ${privateKeyFile}) (also contains public key)"

    if (( verifyKeys )); then
        echo
        echo "$(ansi bold Verifying keys)"
        echo
        verifyAgeKeyPair "${privateKeyFile}" "${publicKeyFile}"
        echo
        echo "$(ansi bold_green Verified) that a file encrypted with $(ansi cyan ${publicKeyFile}) decrypts with passphrase and $(ansi cyan ${privateKeyFile})."
    fi
}

generatePass() {
    echo "$(ansi bold_yellow TODO): implement generatePass()!" # TODO!!
    echo
}

createKeyDocument() {
    local options=
    echo
    echo "$(ansi bold Generating documentation)"
    echo
    generatePdf
    echo
    echo "Keys documented in $(ansi cyan ${documentsFile})"
    open "${documentsFile}" &> /dev/null
}

generatePdf() {
    local workDir=$(tempDirPath)

    # Set armoredKey var

    armorAgeFile "${privateKeyFile}" armoredKey

    # Copy asset files

    for assetFile in "${assetFiles[@]}"; do
        cp "${valtEtcDir}/${assetFile}" "${workDir}/${assetFile}" || fail
    done

    if [[ ${cssOverrideFile} ]]; then
        cp "${cssOverrideFile}" "${workDir}/${cssOverrideFileName}" || fail
    fi

    # Create QR code

    qrCodeFile="${workDir}/${qrCodeFileName}"
    echo "${armoredKey}" | qrencode -l H -o "${qrCodeFile}" || fail
    assertFileExists "${qrCodeFile}"

    # Generate substituted html file

    htmlFile="${workDir}/${htmlFileName}"
    generateHtml "${htmlFile}"
    assertFileExists "${htmlFile}"

    # Move to work dir so that relative paths in html work correctly

    cd ${workDir} || fail

    # Convert html to pdf

    wkhtmltopdf --enable-local-file-access \
        --enable-forms \
        --footer-left "${author} Private Key" \
        --footer-center "$(date '+%B %e, %Y')" \
        --footer-right "Page [page] of [topage]" \
        --footer-font-name "Helvetica, Arial, sans-serif" \
        --footer-font-size 8 \
        "${htmlFile}" "${documentsFile}"

    # Set metadata and encrypt with a strong password

    local title='Private Key Pair Backup & Usage Instructions'
    local creator="$(projectVersion valt), ${valtProjectUrl}"
    local subject="File decryption."
    local keywords="${author}, valt, private key, backup, encryption, decryption, security"

    exiftool \
        -Title="${title}" \
        -Author="${author}" \
        -Subject="${subject}" \
        -Keywords="${keywords}" \
        -Creator="${creator}" \
        -overwrite_original \
        "${documentsFile}"  > /dev/null

    # Encrypt with a strong owner password so that permissions cannot be changed, ensuring
    # that the user password is empty so viewing does not require a password. The owner
    # password should never be required. Note that if we ever want actual form fields,
    # the --modify option must be changed to allow filling.

    local ownerPW="$(phraze)"
    local userPW=''

    qpdf ${documentsFile} \
        --encrypt "${userPW}" "${ownerPW}" 256 --modify=none -- \
        --replace-input
}

generateHtml() {
    local outputFile="${1}"
    local html="$(< ${htmlTemplateFile})" || fail
    local contact value

    # Set built-in substitution values(clobbering any that the user might have defined)

    local _DATE="$(date "+%B %d, %Y %r %Z")"
    local _CSS_PATH="${cssMainFileName}"
    local _LOGO_PATH="${logoFileName}"
    local _QR_CODE_PATH="${qrCodeFileName}"
    local _ARMORED_KEY="${armoredKey}"
    local _CSS_OVERRIDE='<!-- placeholder -->'
    if [[ ${cssOverrideFile} ]]; then
        _CSS_OVERRIDE="<link rel="stylesheet" href="${cssOverrideFileName}">"
    fi

    # Transform contacts into list items

    local _CONTACTS_LIST=
    for contact in "${contacts[@]}"; do
        _CONTACTS_LIST+="<li>${contact}</li>"
    done

    # Collect all required substitution keys (consumes tempHtml)

    local tempHtml="${html}"
    local requiredSubstitutionKeys=()

    while [[ ${tempHtml} =~ ([^{]*)\}(.*) ]]; do
        requiredSubstitutionKeys+=("${BASH_REMATCH[1]}")
        tempHtml="${BASH_REMATCH[2]}"
    done

    # Perform the substitutions, failing if a required substitution is not defined

    for key in "${requiredSubstitutionKeys[@]}"; do
        value="${!key}"
        [[ -v key ]] || fail "${key} not set in ${keyInfoFile}"
        [[ -n "${value}" ]] || fail "${key} value not set in ${keyInfoFile}"
        html=${html/\$\{${key}\}/${value}}
    done
    echo "${html}" > "${outputFile}"
}

main "${@}"
