#!/usr/bin/env bash

# Secure archives.
# Use via: require 'valt/archive'

###############################################################################################################################
#
# ◇ DESIGN NOTES
#
# Archive tar is signed using minisign and encrypted with Age. Encryption provides confidentiality, signature provides
# authenticity/integrity:
#
#   - Files can be stored somewhere less trusted (cloud, shared NAS).
#   - Corruption or tampering can be detected with confidence.
#   - Provide a formal provenance chain, could matter for legal/financial docs.
#
# ◇ Valt File Structure
#
#   my-files.valt
#   │
#   ├── encrypted.tar.xz.age
#   │   ├── payload.tar
#   │   ├── payload.tar.minisig
#   │   ├── payload.minisign.pub
#   │   ├── age.pub
#   │   └── readme.txt
#   ├── encrypted.tar.xz.age.minisig
#   ├── minisign.pub
#   ├── age.pub
#   └── readme.txt
#
# The encrypted tar structure ensures there is always a valid payload signature to use even if the outer one is missing or
# tampered with. The clear files are present for single-file convenience. The readme is from a template that includes generic
# description, metadata and instructions along with user supplied content.
#
# Only tar, minisign and rage (or similar) are required for access, valt automates for convenience.
#
# While .valt files should be safe to distribute publicly, users will likely prefer to distribute privately. To support this
# case and to ensure availability of the clear files, a copy is created without the encrypted tar. This can (and should) be made
# publicly available:
#
#   my-files.valt.pub
#   │
#   ├── encrypted.tar.age.minisig
#   ├── minisign.pub
#   ├── age.pub
#   └── readme.txt
#
# ◇ Valt Keys
#
# Age supports '#' comments in both public and private keys. A valt key is passphrase encrypted and contains both minisign
# keys and Age public key as comments, along with Age private key. A valt public key is clear and is an Age public key with
# minisign public key as comment(s). Generated by valt keys command which uses 'valt/keys' library to construct.
#
#   valt.key: single, secure private key used by valt for signing and decryption
#   valt.pub: single public key used by valt for signature verification and encryption
#
# All keys can be extracted from valt.key, and signature verification and encryption functions will accept the private key.
#
# ◇ Example valt.pub
#
#   # created: 2026-03-10T16:57:47-07:00
#   #
#   # [minisign.pub] untrusted comment: minisign public key 86DA637D4FBBE4E5
#   # [minisign.pub] RWTl5LtPfWPahiYfMcUk9+c/cFAfruNplL79ijRei9i1HzJlDa741qHp
#   #
#   age1kqkzh9m0a2nhwypk3v6cj0fh78qdur5knkzcl4nwpxlh5pyuq33qyhauur
#
# ◇ Example valt.key prior to encryption (not stored)
#
#   # created: 2026-03-10T16:57:47-07:00
#   #
#   # [minisign.pub] untrusted comment: minisign public key 86DA637D4FBBE4E5
#   # [minisign.pub] RWTl5LtPfWPahiYfMcUk9+c/cFAfruNplL79ijRei9i1HzJlDa741qHp
#   #
#   # [minisign.key] untrusted comment: minisign encrypted secret key
#   # [minisign.key] RWQAAEIyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5eS7T31j2oY/107MD2HNm7M18rU0E4aphJJ5b0iNep0Tk/2pgFY5biYfMcUk9+c/cFAfruNplL79ijRei9i1HzJlDa741qHpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
#   #
#   # public key: age1kqkzh9m0a2nhwypk3v6cj0fh78qdur5knkzcl4nwpxlh5pyuq33qyhauur
#   AGE-SECRET-KEY-1KVCTA4K9RSW85YHCSE62L9XJ2ULTPG9ZVRF7K6KGGALCGYUDFHGQY2SYX7#
#
# ◇ Example valt.key
#
#   -----BEGIN AGE ENCRYPTED FILE-----
#   YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCBaQVZVdnlUM3MrL3ExeTRr
#   Ym0wZ0lBIDE5CkNBczlucVdQTy9vV1dzeXNMTDNhNmRqbDhzcFdHWXdWbVlFSHhz
#   UWxHdXMKLS0tIHhLSHJ6eVphelR0QlJjTGFhVkJDYUpwbE5HS3BrNVBhbzI2R3R3
#   aVB6Z2cKJZaL7hk5rEA/2U9PoErZyRGCs6zc6hkx1h6Edu3xXbCcv+Ha03gukMH1
#   YC+UyqpcgdVux7QZwDcUBzn4bRu70HpfPwh9Tn+lXZFA5ntp3nX9+o48gzu6CMDO
#   0E5Mg/OQPDr0myDkPZkek7eXDS34LmvFAndIJI2KE5OOHWQOMs8ga+K+GIT5/uzi
#   ylwiC4kCwA9a1C0nwCfJrKLwkh2ll6j6djV7i/4b8QWcrg8BE8TgpnRKXmmRSLnn
#   eS21HEnUQk76z9wdGDNB+tn5cUsKKs92ghPBOh1jWdkGWDK9TFyPN35nFlpou/hC
#   O+O9QMWkJdoTerhSDmvWPNjIm/mLtojz673Cg6xRMdqhHfQ7Sv2Kw3yTjLxLTCyM
#   ZZGpj/Eww37Tdx7elQQ0BGZGl6gkU7jp3+BOZZgDFD2GIkRqix/LxCg0dPq+g8/b
#   Q162GLCpnCz1wGUyUY4HkadfE3zg4A++TUMwE+dodWKcShGX8BKVEhUclH8B5pKS
#   YAoFAbvMs8DIqycnc6A0zu7ouwaZQkNfIkmpPlsG/fTi6mHH3NbQguEioDKVkIfY
#   rrgDWuPuUst6dEoc1NTbhmDzk/D37ipUZUAKHWong/PG8ljZLkRwfvm6hI9UcuW9
#   lSusKKsVxILzF0PPXfzfxBMQ+jY2+pIRot5QbdItxAuc7UTGzpeKkRQ7Q6XoAle8
#   vHJrI6+OdAl7nnQJrUhO8HZDYyxqTyZpQ68+8ArVyK1n5LtJNJq3vp2+vr2OgNKW
#   ws0fdSu5PqvLoBCPBpAiXyWfy+35tipweu1qw8CwL4CqBlZStr+oA7K2ZVBTpFyk
#   fRZrtCfkQK025fmjOBzwbhU5hbSsK/wlbwiZi1FX6m2pHnC5n+ypLy4xU1oTmvYa
#   ztTsiA==
#   -----END AGE ENCRYPTED FILE-----
#
# ◇ Passphrase Encryption
#
# Users are shown password/phrase advice on key gen to encourage strong, memorable passphrase use, then asked if they already
# have one. If no, then shown a set of generated ones to choose from. This behavior is suppressed after second key gen.
#
# ◇ Valt Key Use
#
#   - Encrypt/sign requires valt.key for PRIVATE signing key and PUBLIC Age key
#   - Decryption requires valt.key for PRIVATE Age key
#   - Verify requires valt.pub, for PUBLIC signing key
#   - Full verify requires valt.key for PUBLIC signing key(s) and PRIVATE Age key
#   - Extract requires valt.key. Warns if sig not verified and asks if should proceed.
#
# ◇ Key Storage
#
#   valt.pub: local, bitwarden (etc.), users github, google drive, iCloud, etc.
#   valt.key: local, bitwarden (etc.)
#
###############################################################################################################################



# Create an encrypted, signed archive from one or more files, directories and archives. Uses the tar file
# specification model.
#
# Usage: newSecureArchive [OPTIONS] <recipients> [ -C <dir> | <file> | <dir> | @<archive> ]...
#
# The -C change directory pattern enables full control over the resulting paths in the archive, e.g.
#
#    -C ${HOME}/my/very/long/path/to/dev/ projectX foo.txt misc/file.txt
#
# cds into the dev directory and adds projectX/**, foo.txt and misc/file.txt at the archive root.
#
# Note that the @<archive> syntax extracts the contents and adds them.
#
# One or more of the following recipients is required, in any combination:
#
#     -R, --recipients-file  PATH       Encrypt to the recipients listed in file at PATH.
#     -v, --valt-recipient   PATH       Encrypt to the recipient in the valt.pub or valt.key file at PATH.
#     -r, --recipient        RECIPIENT  Encrypt to the specified Age public key string.
#
# Options:
#
#     -d, --dest-dir       Specify the archive destination directory (default: ${PWD}).
#     -n, --name NAME      Specify the archive file name prefix (default: ${USER}).
#     -t, --timestamp      Add a timestamp to the archive file name.
#     -z, --timezone NAME  Specify the timezone to use for timestamps, e.g. 'America/Los_Angeles'.
#     -u, --user-text      User text to include in readme. Can contain '\n'.
#     -f, --force          Replace any existing archive file without asking.

newSecureArchive() {
    local tarArgs=()
    local recipients=()
    local fileCount=0
    local i path

    # Options
    local destDir="${PWD}"
    local name="${USER}"
    local timeZoneName='UTC'
    local addTimeStamp=0
    local force=0
    local readmeText=

    # Parse options

    while (( ${#} > 0 )); do
        case "$1" in
            -C ) shift; tarArgs+=(-C "$1") ;;
            -d | --dest-dir) shift; assertDirectory "$1"; destDir="$1" ;;
            -v | --valt-recipient) shift; recipients+=(-r "${ extractRecipient "$1"; }")  ;;
            -r | --recipient) shift; _assertArchiveRecipient "$1"; recipients+=(-r "$1") ;;
            -R | --recipients-file) shift; assertFile "$1" "recipients file"; recipients+=(-R "$1") ;;
            -n | --name) shift; name="$1" ;;
            -t | --timestamp) addTimeStamp=1 ;;
            -z | --timezone) shift; timeZoneName="$1" ;;
            -f | --force) force=1 ;;
            -u | --user-text) shift; readmeText="$1" ;;
            *) tarArgs+=("$1"); (( fileCount++ )) ;;
        esac
        shift
    done

# TODO:
#
#    Implementation gap vs. design: The current _createEncryptedArchive pipes tar | rage directly, but signing requires the tar on disk first. The actual flow needs to be:
#    1. Create payload.tar to temp
#    2. Minisign payload.tar → .minisig
#    3. Bundle payload + sig + keys + readme into inner tar
#    4. Encrypt inner tar with rage → encrypted.tar.xz.age
#    5. Minisign the .age file → outer .minisig
#    6. Bundle everything into the outer .valt tar
#
#    Signing key extraction: To sign, valt needs the minisign private key out of the passphrase-encrypted valt.key. That means decrypting it first, extracting the embedded key, using it,
#    then clearing it. This is where the FIFO passphrase flow we discussed becomes relevant — you'll need the passphrase after rage finishes decrypting.
#
#
#  minisign dependency: Not yet in flake.nix / rayvn.pkg.
#

    # Make sure we have one or more recipients

    [[ ${#recipients[@]} ]] || fail "no recipients specified"

    # Make sure we have one or more files to add

    (( fileCount )) || fail "no files to add"

    # Add timestamp to name if requested

    (( addTimeStamp )) && name+="-${ TZ=${timeZoneName} date +%Y-%m-%d_%H.%M; }"

    # Ok we're good to go, so create file names, temp tar dir and result file

    local encryptedTarName="${name}.${tarFileExtension}.${ageFileExtension}" # tar.xz.age
    local envelopeTarName="${name}.valt"
    local encryptedTarFile; encryptedTarFile="${ tempDirPath ${encryptedTarName}; }"
    local archiveFile="${destDir}/${envelopeTarName}"

    # TODO: readme

    # If result file exists, delete it if force or user confirms

    _removeExistingArchiveFile

    # Create the encrypted archive file

    _createEncryptedArchive

    mv "${encryptedTarFile}" .; ls -l ${encryptedTarName} # TODO remove
}

verifySecureArchive() {
    assertFile "$1"
    local keyFile="$1"
    local keyIsPrivate="${2:-false}" # True means full verification with decryption.
    # rayvnTest_ValtKeyPassphrase var can be set for testing.

    echo ; # TODO!!
}

extractSecureArchive() {
    echo ; # TODO!!
}


PRIVATE_CODE="--+-+-----+-++(-++(---++++(---+( ⚠️ BEGIN 'valt/archive' PRIVATE ⚠️ )+---)++++---)++-)++-+------+-+--"


_init_valt_archive() {
    require 'rayvn/core' 'valt/keys'
}

_assertArchiveRecipient() {
    local recipient="$1"
    if [[ ${recipient} != age* ]]; then
        if [[ -f ${recipient} ]]; then
            fail "${recipient} is not a public key but is a file, use -R instead of -r"
        else
            fail "${recipient} is not a public key"
        fi
    fi
}

_removeExistingArchiveFile() {
    if [[ -e "${archiveFile}" ]]; then
        if (( ! force )); then
            local answer
            show primary "${archiveFile}" off "already exists."
            prompt "${ show -n primary "${archiveFile}" off "already exists. Replace it?" ;}" yes no answer
            [[ ${answer} == "yes" ]] || exit 0
        fi
        rm "${archiveFile}" || fail
    fi
}

_createEncryptedArchive() {
debugVar tarArgs recipients encryptedTarFile
    # TODO: the -H pax arg for extended headers is gnu-tar. Worth it for new dependency?
    tar cJ "${tarArgs[@]}" | rage "${recipients[@]}" > ${encryptedTarFile} || fail
}


